openapi: 3.0.0
info:
  title: Football Competition Management API
  version: 1.0.0
  description: API for managing football competitions, teams, and players.

servers:
  - url: http://api.STD23082.com

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          description: Name of the competition.
        location:
          type: string
          description: Country or continent where the competition takes place.

    Team:
      type: object
      properties:
        name:
          type: string
          description: Name of the team.
        slogan:
          type: string
          description: Slogan of the team.
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        name:
          type: string
          description: Name of the player.
        number:
          type: integer
          description: Player's number.
        strongFoot:
          type: string
          enum:
            - Left
            - Right
          description: Player's strong foot.

paths:
  /competitions:
    get:
      summary: Get list of competitions
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        200:
          description: List of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'

    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        201:
          description: Competition created

  /teams:
    get:
      summary: Get list of teams
      parameters:
        - name: teamName
          in: query
          schema:
            type: string
          description: Filter teams by name.
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        200:
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        201:
          description: Team created

  /players:
    get:
      summary: Get list of players
      parameters:
        - name: playerName
          in: query
          schema:
            type: string
          description: Filter players by name.
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
          description: Number of items per page.
      responses:
        200:
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

    post:
      summary: Create a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        201:
          description: Player created
